# Generated by Django 6.1.1 on 2026-09-28 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='x',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='x',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='x',
            index=models.Index(fields=['-created_at'], name='x_x_created_caf5a4_idx'),
        ),
        migrations.AddIndex(
            model_name='x',
            index=models.Index(fields=['user', '-created_at'], name='x_x_user_id_c348b4_idx'),
        ),
    ]
